# การหาปริพันธ์ (Integrations)

## ปฏิยานุพันธ์ (Antiderivatives)

จากเรื่องการหาอนุพันธ์ ถ้าวัตถุชนิดหนึ่งมีสมการการเคลื่อนที่ คือ $s = t^{3}$
โดยที่วัตถุนี้เคลื่อนที่ได้ระยะทาง $s$ เมตร เมื่อเวลาผ่านไป $t$ วินาที
แล้วเราสามารถบอกได้ว่าวัตถุเคลื่อนที่ด้วยความเร็ว $v = 
3t^2$ เมตร/วินาที แต่เรารู้ว่า $\displaystyle v = \frac{ds}{dt}$ ดังนั้น
$\displaystyle  \frac{ds}{dt} = 3t$
ในทางกลับกันถ้าเรารู้ว่าสมการความเร็วของวัตถุชนิดหนึ่ง ถ้า $v = 3t^{2}$ แสดงว่า
$\displaystyle \frac{ds}{dt} = 3t^2$
แล้วลองนึกย้อนกลับว่าสมการการเคลื่อนที่ของวัตถุชนิดนี้ คือ สมการใด
จะเห็นว่าสมการการเคลื่อนที่ของวัตถุนี้อาจจะอยู่ในรูป $$\begin{aligned}
    s &= t^3 \\ 
    s &= t^3 -2 \\
    \text{หรือ  } s &= t^3 + 5
\end{aligned}$$ ซึ่งทั้งสามสมการนี้มี $\displaystyle  \frac{ds}{dt}= 3t^2$
แต่เราก็ยังไม่แน่ใจว่าเป็นสมการใดกันแน่หรืออาจไม่ใช่ทั้งสามสมการนี้ก็ได้
แต่เราสามารถคาดคะเนได้ว่าสมการการเคลื่อนที่ของวัตถุนี้ควรจะอยู่ในรูป $$s = t^{3} + c$$
โดยที่ $c$ เป็นค่าคงตัว สมการการเคลื่อนที่ทั้งสี่สมการดังกล่าวนี้เป็นตัวอย่างของ "ปฏิยานุพันธ์"
ของ $v = 3t^{2}$

ในกรณีทั่วไป เราจะนิยามปฏิยานุพันธ์ของฟังก์ชันดังต่อไปนี้

::: definition
ฟังก์ชัน $F$ เป็นปฏิยานุพันธ์ (antiderivative) ของฟังก์ชัน $f$ บนช่วง $I$ ถ้า
$F'(x) = f(x)$ สำหรับทุก ๆ ค่าของ $x$ ในช่วง $I$
:::

::: example
จงแสดงว่า $F(x) = x^{2}-2x- 3$ เป็นปฏิยานุพันธ์ของฟังก์ชัน $f(x)=2x-2$ บนช่วง
$\left( {-\infty ,\infty } \right)$
:::

**วิธีทำ** จาก $F(x) = x^{2} - 2x - 3$ จะได้ $F'(x) 
= 2x - 2$ นั่นคือ $F'(x) = f(x)$ สำหรับทุก ๆ $x$ ในช่วง $\left( {-\infty 
,\infty } \right)$

::: example
ให้ $f(x) = 2x^{3/2}$ จงหาปฏิยานุพันธ์ของ $f$ บนช่วง
$\left( {0 ,\infty } \right)$
:::

**วิธีทำ** ให้ $\displaystyle F_{1}(x) = \frac{4}{5} x^{5/2}$ จะได้
$F'_1(x) = 2x^{3/2}$ สำหรับ $x > 0$

และให้ $\displaystyle F_{2}(x) = \frac{4}{5} x^{5/2} + 2$ จะได้
$F'_2(x) = 2x^{3/2}$ สำหรับ $x > 0$

และให้ $\displaystyle F_{3}(x) = \frac{4}{5} x^{5/2} - 5$ จะได้
$F'_3(x) = 2x^{3/2}$ สำหรับ $x > 0$

ดังนั้น $F_1,F_2$ และ $F_3$ ต่างก็เป็นปฏิยานุพันธ์ของ $f(x) = 2x^{3/2}$ บนช่วง
$\left( {0 ,\infty } \right)$ และแต่ละค่าคงตัว $C$ ถ้าให้
$F(x) =(4/5)x^{5/2} + C$ จะทำให้ $F'(x) = 2x^{3/2}$ สำหรับทุก
$x \in \left( 0 ,\infty  \right)$

ดังนั้น เราสามารถสรุปได้ว่าฟังก์ชัน $F$ ใด ๆ ที่ $$\label{eq111} 
    F(x) = \frac{4}{5} x^{5/2} + C$$ เป็นปฏิยานุพัน์ของ $f(x) = 2x^{3/2}$
บนช่วง $\left( 0 ,\infty  \right)$ เมื่อ $C$ เป็นค่าคงตัว

จากตัวอย่างนี้ฟังก์ชัน $F$ ที่นิยาม โดย ([\[eq111\]](#eq111){reference-type="ref"
reference="eq111"}) เป็นรูปทั่วไปของปฏิยานุพันธ์ของ $f(x) = 2x^{3/2}$ บน
$\left( 0 ,\infty  \right)$ และให้สังเกตว่าช่วง $\left( 0 
,\infty  \right)$ เป็นโดเมนของ $f$

**ข้อสังเกต**

1.  ถ้า $f$ และ $g$ เป็นฟังก์ชันซึ่ง $f^{'}(x) = g^{'}(x)$ สำหรับทุก ๆ $x$ ในช่วง
    $I$ แล้วจะมีค่าคงที่ $K$ ที่ทำให้ $f(x) = g(x) + K$

2.  ถ้า $F$ เป็นปฏิยานุพันธ์เฉพาะของ $f$ บนช่วง $I$ แล้วแต่ละปฏิยานุพันธ์ของ $f$
    บนช่วง สามารถถูกเขียนได้ในรูป $F(x) + C$ เมื่อ $C$ เป็นค่าคงตัว

### แบบฝึกหัด {#prob-anti}

จงหาปฏิยานุพันธ์ของฟังก์ชันที่กำหนดให้ดังต่อไปนี้

:::: enumerate
::: multicols
2

$f(x) = 0$

$f(x) = 4x$

$f(x) = 3x^{2 }$

$f(x) = x^{3}$

$f(x) = \sqrt{x}$

$f(x) = e^{x}$

$f(x) = \sin x$

$f(x) = \frac{1}{x^{2}+1}$
:::
::::

**เฉลยแบบฝึกหัด** [1.1.1](#prob-anti){reference-type="ref"
reference="prob-anti"} กำหนดให้ $C$ แทนค่าคงตัวใด ๆ

::: multicols
2

1.  $C$

2.  $2x^{2} + C$

3.  $x^{3} + C$

4.  $\displaystyle \frac{x^{4}}{4}+c$

5.  $\displaystyle \frac{2x^{3/2}}{3} + C$

6.  $e^{x} + C$

7.  $-\cos x + C$

8.  $\tan^{-1}x + C$
:::

## ปริพันธ์จำกัดเขต (The Definite Integral)

### Integration คืออะไร

Integration Calculus เป็นวิชาที่เกี่ยวกับการคำนวณหา
พื้นที่และปริมาตรของรูปทรงต่างๆโดยอาศัยหลัก การที่ว่า รูปทรงใดๆเกิดจากการ
ประกอบกันของชิ้นส่วนเล็กๆจำนวนมากมาย (infinity) ในบทนี้เราจะศึกษา เกี่ยวกับ

-   การประมาณค่าพื้นที่

-   The definite integral

-   ทฤษฎีเบื้องต้น และทฤษฎีพื้นฐานของแคลคูลัส

### การประมาณค่าพื้นที่และปริพันธ์จำกัดเขต

พิจารณาฟังก์ชัน $y=f(x) \ge 0$ บนช่วงเปิด $[a,b]$
ถ้าเราต้องการประมาณค่าพื้นที่ที่ล้อมรอบด้วยส่วนโค้ง $y=f(x)$ แกน $x$ และเส้นตรง
$x=a\;,\;x=b$\

<figure>

<figcaption>การประมาณค่าพื้นที่</figcaption>
</figure>

วิธีการหนึ่งที่ทำได้ก็คือ การหาผลรวมของพื้นที่รูปสี่เหลี่ยมผืนผ้าที่มาประกอบกันคุมพื้นที่ดังรูป
ยิ่งขนาดของรูปสี่เหลี่ยม ผืนผ้าเล็กมากๆ
ความถูกต้องของการประมาณค่าจะยิ่งใกล้เคียงค่าจริงยิ่งขึ้น
แนวคิดเกี่ยวกับการประมาณค่าโดยอาศัยรูปสี่เหลี่ยมผืนผ้านั้นเป็นวิธีการพื้นฐานที่ใช้ในการคำนวณหาพื้นที่ใต้ส่วนโค้ง
การหาพื้นที่ $A$ ที่ล้อมรอบด้วย ส่วนโค้ง $y=f(x)$ แกน $x$ และเส้นตรง $x=a\;,\;x=b$
เราต้องแบ่งช่วง $[a,b]$ ออกเป็น $n$ ช่วงเล็กๆขนาด เท่ากันคือ $\frac{b-a}{n}$
สำหรับ $I=0,1,2,…,n-1$
ลากเส้นตรงแนวดิ่งตัวส่วนโค้งและสร้างรูปสี่เหลี่ยมผืนผ้าทางด้านขวาของ เส้นตรงแนวดิ่งนี้
จะได้ว่าความสูงของสี่เหลี่ยมผืนผ้ารูปที่ $I$ คือ $f(x_i)$ และ พื้นที่ของสี่เหลี่ยมผืนผ้ารูปที่
$\;I\;$ คือ $\;\;\frac{b-a}{n}\times f(x_i)\;\;$ ดังนั้น
พ.ท.ทั้งหมดของสี่เหลี่ยมผืนผ้า $n$ รูป คือ
$$A(n)= \sum_{i=0}^{n-1}\frac{b-1}{n}f(x_i)$$ โดยที่
$x_i = a + \frac{i}{n}(b-a)$

ขณะที่จำนวนของช่วงย่อยต่างๆเพิ่มขึ้น ขนาดของช่วงย่อยเหล่านี้คือ $\frac{b-a}{n}$ จะลดลง
และพื้นที่ $A(n)$ จะเข้าใกล้ พื้นที่ $A$ ที่เราต้องการคำนวณ ดังนั้นพื้นที่ $A$
สามารถหาค่าได้จากสมการข้างล่างนี้
$$A= \lim\limits_{n\rightarrow\infty}\sum_{i=0}^{n-1}\frac{b-a}{n}f(x_i)$$

<figure>

</figure>

ถ้าเรากำหนดให้ $\Delta x=\frac{b-a}{n}$ นิยามของการ integrate คือ
$\int^b_af(x)dx=
\lim\limits_{\Delta\rightarrow 0}\sum_a^bf(x_i)\Delta x$\
โดยที่ $a$ และ $b$ เป็นลิมิตของการอินทิเกรท และสัญลักษณ์ $\int^b_af(x)dx$ เป็นจำนวน
ไม่ใช่ฟังก์ชัน และเรียกสัญลักษณ์นี้ว่า definite integral

::: example
จงคำนวณหาพื้นที่ ที่ล้อมรอบด้วยส่วนโค้ง $y=x^2$ เส้นตรง $x=0,x=4$ และแกน $x$
:::

**วิธีทำ** สูตรสำหรับประมาณค่าพื้นที่ คือ $\sum_{i=0}^{n-1}\frac{b-a}{n}f(x_i)$

**กรณีที่ 1** : ใช้รูปสี่เหลี่ยมผืนผ้า 4 รูป

เรามี $f(x)=x^2\;\;,\;\;a=0\;\;,\;\;b=4\;\;,\;\;n=4\;\;\;$ และ

$x_0=0\;\;,\;\;x_1=1\;\;,\;\;x_2=2\;\;,\;\;x_3=3\;\;$ จะได้ว่า\
พื้นที่โดยประมาณคือ

$[1\times (0)^2]+[1\times (1)^2]+[1\times (1)^2]+ [1\times (3)^2]$

$=[0]+[1]+[4]+[9]=14$

**กรณีที่ 2** : ใช้รูปสี่เหลี่ยมผืนผ้า 8 รูป\
พื้นที่โดยประมาณคือ

$[1\times (0)^2]+[0.5\times (0.5)^2]+[0.5\times (1)^2]+ [0.5\times (1.5)^2]+ [0.5\times (2)^2]+ [0.5\times (2.5)^2]+ [0.5\times (3)^2]= [0.5\times (3.5)^2]$\
$=[0]+[0.125]+[0.5]+[1.125]+[2]+[3.125]+[4.5]+[6.125]=17.5$

<figure>

<figcaption>การประมาณค่าพื้นที่ที่ล้อมรอบด้วยส่วนโค้ง <span
class="math inline"><em>y</em> = <em>x</em><sup>2</sup></span> เส้นตรง
<span class="math inline"><em>x</em> = 0, <em>x</em> = 4</span> และแกน
<span class="math inline"><em>x</em></span></figcaption>
</figure>

## ทฤษฎีพื้นฐานของแคลคูลัส (The fundamental Theorem of Calculus)

วิชาแคลคูลัสแบ่งออกเป็น 2 สาขา คือ แคลคูลัสที่เกี่ยวกับการหาอนุพันธ์
ซึ่งถือกำเนิดมาจากความต้องการที่จะหาความชันของฟังก์ชัน และแคลคูลัส ที่เกี่ยวกับการอินทิเกรท
ซึ่งถือกำเนิดมาจากความต้องการที่จะหาพื้นที่ใต้กราฟ

ทฤษฎีพื้นฐานของแคลคูลัสเป็นทฤษฎีที่เป็นตัวเชื่อมระหว่าง 2 สาขาทางแคลคูลัส
และใช้แสดงความเกี่ยวเนื่องของการหา antiderivative ของฟังก์ชันหนึ่งกับการคำนวณหา
definite integral ของฟังก์ชันนั้น
$$\int^b_af(x)dx= \lim\limits_{\Delta\rightarrow 0}\sum_a^bf(x_i)\Delta x$$
เราใช้สัญลักษณ์ $\int f(x)dx$ แทน antiderivative ของฟังก์ชัน $f(x)$
และเรียกสัญลักษณ์นี้ว่า indefinite integral

::: theorem
$( \mbox{ทฤษฎีพื้นฐานของแคลคูลัส})$ ถ้า $f$ เป็นฟังก์ชันต่อเนื่องในช่วง $[a,b]$ แล้ว

1.  ถ้า $\displaystyle g(x)=\int_{a}^{x}f(t) \ dt$ แล้ว $g'(x)=f(x)$

2.  $\displaystyle \int_{a}^{b}f(x) \ dx=F(b)-F(a)$ เมื่อ $F$ คือ
    antiderivative ของ $f$
:::

**ข้อสังเกต** ข้อสรุป 1. ในทฤษฎีข้างต้นสามารถเขียนในรูป

::: center
$\displaystyle \frac{d}{dx}\left(\int_{a}^{x}f(t) \ dt\right)=f(x)$
:::

::: example
จงหาอนุพันธ์ของ $\displaystyle 
g(x)=\int_{0}^{x}\sqrt{1+t^{4}} \ dt$
:::

**วิธีทำ** เนื่องจาก $\displaystyle f(t)=\sqrt{1+t^{4}}$ เป็นฟังก์ต่อเนื่อง

ดังนั้น จากทฤษฎีพื้นฐานของแคลคูลัส $\displaystyle 
\frac{d}{dx}\left(g(x)\right)=\sqrt{1+x^{4}}$

::: example
จงหา $\displaystyle \frac{d}{dx}\int_{0}^{x^{2}}\sin t \ dt$
:::

**วิธีทำ** ให้ $U=x^{2}$ ดังนั้น

$\qquad \qquad \ \displaystyle \frac{d}{dx}\int_{0}^{x^{2}}\sin t \ dt 
=\frac{d}{dx}\int_{0}^{U}\sin t \ dt$

$\qquad \qquad \qquad \qquad \qquad \quad =\displaystyle 
\frac{d}{dU}\left(\int_{0}^{U}\sin t \ dt\right) \frac{dU}{dx} \quad ( 
\mbox{โดยกฎลูกโซ่})$

$\qquad \qquad \qquad \qquad \qquad \quad =\displaystyle \sin U \,
\frac{dU}{dx} \quad ( \mbox{โดยทฤษฎีพื้นฐานทางแคลคูลัส} )$

$\qquad \qquad \qquad \qquad \qquad \quad =\displaystyle \sin x^{2}\cdot 2x$

$\qquad \qquad \qquad \qquad \qquad \quad =\displaystyle 2x\cdot \sin x^{2}$

::: example
จงหา $\displaystyle \int_{0}^{2}e^{x} \ dx$ โดยใช้ทฤษฎีพื้นฐานทางแคลคูลัส
:::

**วิธีทำ** เนื่องจาก $F(x)=e^{x}$ เป็น antiderivative ของ $f(x)=e^{x}$ และ
$f(x)$ เป็นฟังก์ต่อเนื่อง ในช่วง $[0,2]$

ดังนั้น $\displaystyle \int_{0}^{2}e^{x}\ dx = F(2)-F(0) =e^{2}-e^{0} = 
e^{2}-1$

### สูตรพื้นฐานของการอินทิเกรท (Basic Integration Rules)

จากทฤษฎีพื้นฐานทางแคลคูลัส (The fundamental Theorem of Calculus) เราทราบว่า ถ้า
$\displaystyle g(x)=\int_{a}^{x}f(t) \ dt$ แล้ว $g'(x)=f(x)$
และจากนิยามของ antiderivative เราสรุปได้ว่า
$\displaystyle g(x)=\int_{a}^{x}f(t) \ dt$ เป็น antiderivative ของ $f(x)$
ซึ่งเรามักจะเขียน $\displaystyle \int f(x) \ dx$ แทน antiderivative ของ
$f(x)$

นั่นคือ

::: center
:::

จากเนื้อหาเรื่องการหาอนุพันธ์ของฟังก์ชันเราทราบว่า
$\displaystyle \frac{d}{dx} \left( \ln |x|+C 
\right)=\frac{1}{x}$ , เมื่อ $C$ เป็นค่าคงที่

ดังนั้นจากคำอธิบายในข้างต้น เราสรุปได้ว่า

$$\displaystyle \int \frac{1}{x} \ dx = \ln|x|+C$$

ในทำนองเดียวกัน
เราสามารถใช้ความรู้เรื่องการหาอนุพันธ์สร้างสูตรพื้นฐานของการอินทิเกรทได้ดังนี้

1.  $\displaystyle \int C f(x) \ dx = C \int f(x) \ dx$ เมื่อ $C$ เป็นค่าคงที่

2.  $\displaystyle \int [f(x)+g(x)] \ dx = \int f(x) \ dx+\int 
    g(x) \ dx$

3.  $\displaystyle \int k \ dx = kx+C \quad$ เมื่อ $k, C$ เป็นค่าคงที่

4.  $\displaystyle \int x^{n} \ dx = \frac{x^{n+1}}{n+1}+C 
    \quad$ เมื่อ $n\neq -1$

5.  $\displaystyle \int \frac{1}{x} \ dx = \ln|x|+C$

6.  $\displaystyle \int e^{x} \ dx = e^{x}+C$

7.  $\displaystyle \int a^{x} \ dx = \frac{a^{x}}{ \ln a}+C 
    \quad$ เมื่อ $a$ เป็นจำนวนบวก และ $a\neq 1$

8.  $\displaystyle \int \sin x \ dx = -\cos x+C$

9.  $\displaystyle \int \cos x \ dx = \sin x+C$

10. $\displaystyle \int \sec^{2} x \ dx = \tan x+C$

11. $\displaystyle \int \csc^{2} x \ dx = -\cot x+C$

12. $\displaystyle \int \sec x \tan x \ dx = \sec x+C$

13. $\displaystyle \int \csc x \cot x \ dx = -\csc x+C$

14. $\displaystyle \int \frac{1}{x^{2}+1} \ dx = \arctan x+C$

15. $\displaystyle \int \frac{1}{\sqrt{1-x^{2}}} \ dx = 
    \arcsin x+C$

::: example
จงหา $\displaystyle \int (9x^{5}-4 \csc^{2} x) \ dx$
:::

**วิธีทำ**

$\qquad \qquad \ \displaystyle \int (9x^{5}-4 \csc^{2} x) \ dx \ = 9\int 
x^{5} \ dx -4 \int \csc^{2} x \ dx \quad ( \mbox{สูตร} \ 1 \ \mbox{และ} \ 
2)$

$\qquad \qquad \qquad \qquad \qquad \qquad \quad \ \ =\displaystyle 
\frac{9}{ 6}x^{6} -4(-\cot x)+C \quad ( \mbox{สูตร} \ 4 \ \mbox{และ} \ 11)$

$\qquad \qquad \qquad \qquad \qquad \qquad \quad \ \ =\displaystyle 
\frac{3}{2}x^{6}+4\cot x+C$

::: example
จงหา $\displaystyle \int \frac{\cos \theta}{\sin^{2} \theta} 
\ d\theta$
:::

**วิธีทำ**

$\qquad \qquad \ \displaystyle \int \frac{\cos \theta}{\sin^{2} \theta} \ 
d\theta \ = \int \left(\frac{1}{\sin \theta}\right) \left(\frac{\cos 
\theta}{\sin \theta}\right) \ d\theta$

$\qquad \qquad \qquad \qquad \qquad = \displaystyle \int \csc \theta \cot 
\theta \ d\theta$

$\qquad \qquad \qquad \qquad \qquad = \displaystyle -\csc \theta +C \quad ( 
\mbox{สูตร} \ 13)$

::: example
จงหา $\displaystyle \int 
\frac{x^{3}+2\sqrt{x}-3}{x^{\frac{3}{2}}} \ dx$
:::

**วิธีทำ** จะเห็นว่า $\displaystyle 
\frac{x^{3}+2\sqrt{x}-3}{x^{\frac{3}{2}}} \ = \ 
\frac{x^{3}}{x^{\frac{3}{2}}}+\frac{2\sqrt{x}}{x^{\frac{3}{2}}}-\frac{3}{x^{\frac{3}{2}}}$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ = \ 
x^{\frac{3}{2}}+2x^{-1}-3x^{-\frac{3}{2}}$

$\qquad \qquad\ \displaystyle \int \frac{x^{3}+2\sqrt{x}-3}{x^{\frac{3}{2}}} 
\ dx \quad \ = \int x^{\frac{3}{2}} \ dx +2 \int x^{-1} \ dx -3 \int 
x^{-\frac{3}{2}} \ dx$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ =\displaystyle 
\frac{x^{\frac{3}{2}+1}}{\frac{3}{2}+1}  + 2 \ln |x| 
-\frac{3x^{-\frac{3}{2}+1}}{-\frac{3}{2}+1} + C$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ =\displaystyle 
\frac{x^{\frac{5}{2}}}{\frac{5}{2}} + 2 \ln 
|x|-\frac{3x^{-\frac{1}{2}}}{-\frac{1}{2}}+ C$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ =\displaystyle 
\frac{2}{5}x^{\frac{5}{2}}+ 2 \ln |x|+\frac{6}{\sqrt{x}}+ C$

::: example
จงหา $\displaystyle \int_{0}^{1} \left( x^{4} - 
\frac{2}{1+x^{2}} \right) \ dx$
:::

**วิธีทำ**

$\qquad \qquad\ \displaystyle \int_{0}^{1} \left( x^{4} - \frac{2}{1+x^{2}} 
\right) \ dx \ = \int_{0}^{1} x^{4} \ dx - 2 \int_{0}^{1} \frac{1}{1+x^{2}} 
\ dx$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ \ =\displaystyle 
\frac{x^{5}}{5} \bigg |_{0}^{1}-2 \arctan x \bigg |_{0}^{1}$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ \ = \displaystyle \left( 
\frac{1}{5} - 0 \right) - 2 \left( \arctan 1 - \arctan 0 \right)$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ \ =\displaystyle 
\frac{1}{5}-2 \left( \frac{ \pi }{4}-0 \right)$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \ \ =\displaystyle 
\frac{1}{5}- \frac{ \pi }{2}$

# เทคนิคของการหาปริพันธ์ (Techniques of Integration)

ในบทนี้เราจะศึกษาวิธีต่างๆ ที่สำคัญในการช่วยหาปริพันธ์ของฟังก์ชันต่างๆ เทคนิคแรก คือ
การเปลี่ยนตัวแปร (the substitution rule) ซึ่งวิธีนี้มีการประยุกต์มาจากกฎลูกโซ่
เทคนิคถัดมา คือ integration by part ซึ่งประยุกต์มาจากการหาอนุพันธ์ของผลคูณของฟังก์ชัน
และเทคนิคสุดท้าย คือ integration by partial fraction โดยการเลือกใช้เทคนิคต่างๆ
จะขึ้นอยู่กับ integrand

## การหาปริพันธ์โดยการเปลี่ยนตัวแปร (Integration by Substitution)

พิจารณา indefinite integral ที่อยู่ในรูปของ $$\int f(g(x))g'(x) dx$$ ถ้ากำหนดให้
$F(x)$ เป็น antiderivative ของ $f(x)$, นั่นคือ $F'(x) = f(x)$
แล้วโดยการใช้กฏลูกโซ่เราจะได้ว่า $$\frac{d}{dx} F(g(x)) = F'(g(x)) g'(x)$$ หรือ
$$\label{eqn-sub}    
            \int F'(g(x)) g'(x) dx = F(g(x)) + C$$ และถ้ากำหนดให้
$u = g(x)$ และพิจารณาสมการที่ [\[eqn-sub\]](#eqn-sub){reference-type="ref"
reference="eqn-sub"} เราจะได้ว่า
$$\int F'(g(x)) g'(x) dx = F(g(x)) + C = F(u) + C = \int F'(u) du$$ หรือ
$$\int f(g(x))g'(x) dx  = \int f(u) du$$

สรุปแล้วเมื่อเราทำการเปลี่ยนตัวแปร $u = g(x)$ เราจะได้ว่า $du = g'(x)dx$ ดังนั้น
$\int f(g(x)) g'(x) dx$ สามารถถูกเขียนให้อยู่ในรูปของ $\int f(u)du$
ซึ่งทำให้สามารถหาปริพันธ์ได้นั่นเอง

::: theorem
ถ้า $u = g(x)$ แล้ว $$\int f(g(x)) g'(x) dx  = \int f(u) du$$
:::

::: example
จงหาปริพันธ์ต่อไปนี้ $\int x^2 (x^3 + 1)^5 dx$
:::

**วิธีทำ** โดยการเปลี่ยนตัวแปร $u = x^3 + 1$ เราจะได้ว่า $du = 3x^2 dx$
ดังนั้นเราสามารถเขียน integral ใหม่ได้ดังนี้ $$\begin{aligned}
        \int x^2 (x^3 + 1)^5 dx &= \int u^5 \frac{1}{3} du \\
                                &= \frac{1}{3}\int u^5 du\\
                                &= \frac{1}{3} \frac{u^6}{6} + C\\
                                &= \frac{1}{18} (x^3+1)^6 + C
        
\end{aligned}$$

::: example
จงหาปริพันธ์ต่อไปนี้ $\int \sqrt{2x + 3} dx$
:::

**วิธีทำ** โดยการเปลี่ยนตัวแปร $u = 2x + 3$ เราจะได้ว่า $du = 2 dx$
ดังนั้นเราสามารถเขียน integral ใหม่ได้ดังนี้ $$\begin{aligned}
        \int \sqrt{2x + 3} dx  &= \int \sqrt{u} \frac{1}{2} du \\
                                &= \frac{1}{2}\int u^{1/2} du\\
                                &= \frac{1}{2} \frac{ u^{3/2}}{3/2} + C\\
                                &= \frac{1}{3} (2x + 3)^{3/2} + C
        
\end{aligned}$$

::: example
จงหาปริพันธ์ต่อไปนี้ $\int \frac{1}{x} (1+ \ln x)^2 dx$
:::

**วิธีทำ** โดยการเปลี่ยนตัวแปร $u = 1 + \ln x$ เราจะได้ว่า $du =  \frac{dx}{x}$
ดังนั้นเราสามารถเขียน integral ใหม่ได้ดังนี้ $$\begin{aligned}
        \int \frac{1}{x} (1+ \ln x)^2 dx  &= \int u^2 du \\
                                &= \frac{u^3}{3} + C\\
                                &= \frac{1}{3} (1 + \ln x)^3 + C
        
\end{aligned}$$

### แบบฝึกหัด {#แบบฝกหด}

จงหาปริพันธ์ต่อไปนี้

1.  $\int \sqrt{x+1} dx$

2.  $\int (x^2 - 2x) \sqrt{x^3 - 3x^2 +1} dx$

3.  $\int \sin x e^{\cos x} dx$

4.  $\int \tan \sec^2 x dx$

5.  $\int \frac{(\ln x)^2}{x} dx$

### การหาปริพันธ์โดยการแทนด้วยฟังก์ชันตรีโกณมิติ (Trigonometric Substitutions)

เราสามารถใช้วิธีการเปลี่ยนตัวแปรเพื่อหาปริพันธ์ของฟังก์ชันในรูปแบบต่อไปนี้

1.  $\int \sin^m x \cos^n x dx$

2.  $\int \tan^m x \sec^n x dx$

3.  $\int \cot^m x \csc^n x dx$

โดยในบทนี้จะยกตัวอย่างเฉพาะในกรณีแรกเท่านั้น ส่วนกรณีที่เหลือสามารถใช้หลักการเดียวกัน

พิจารณาจากตัวอย่างต่อไปนี้

::: example
จงหาปริพันธ์ต่อไปนี้ $\int \sin^3 x \cos x dx$
:::

**วิธีทำ** โดยการเปลี่ยนตัวแปร $u = \sin x$ เราจะได้ว่า $du = \cos x dx$ ดังนั้น
$$\int \sin^3 x \cos x dx = \int u^3 du = \frac{1}{4}u^4 + C = \frac{1}{4} \sin ^4 x + C$$

ในกรณีของ integral แบบแรก $\int \sin^m x \cos^n x dx$
เราจะแบ่งการพิจารณาเป็น 2 กรณี ดังนี้

**กรณีที่ 1** ถ้า $m$ หรือ $n$ อย่างน้อยหนึ่งตัวที่เป็นจำนวนบวกคี่ สมมติให้ $m$
เป็นจำนวนบวกคี่ ดังนั้นเราสามารถที่จะเขียน $m = 2k +1$ เราจะแยก $\sin x$ ออกมาจาก
$\sin^{2k} x$ และจะใช้เอกลักษณ์ $\sin^2 x = (1 - \cos^2 x)$ ในการจัดรูป
integral ดังนี้ $$\begin{aligned}
        \int \sin^m x \cos^n x dx &= \int (\sin^{2}x)^k \cos^n x \sin x dx \\
                                    &= \int (1 - \cos^2 x)^k \cos^n x \sin x dx \\
                                    &= - \int (1 - u^2)^k u^n du 
    
\end{aligned}$$ โดยเรากำหนดให้ $u = \cos x$ สังเกตว่า integral
สุดท้ายจะง่ายต่อการหาอนุพันธ์

::: example
จงหาปริพันธ์ของ $\int \sin^3 x \cos^3 x dx$
:::

**กรณีที่ 2** ถ้า $m$ และ $n$ เป็นจำนวนบวกคู่
ในกรณีนี้เราสามารถที่จะใช้เอกลักษณ์ตรีโกณมิติต่อไปนี้ในการทำให้ integral
อยู่ในรูปที่ง่ายต่อการหาค่าปริพันธ์
$$\sin^2 x = \frac{1}{2}(1-\cos 2x) \quad  \cos^2 x = \frac{1}{2}(1 + \cos 2x)$$
โดยพิจารณาจากตัวอย่างต่อไปนี้

::: example
จงหาปริพันธ์ของ $\int \sin^2 x \cos^2 x dx$
:::

## การหาปริพันธ์โดยแยกส่วน (Integration by Parts)

ในบทนี้เราจะใช้การแปลง (transformation) ในการเปลี่ยนรูปของ integral
บางประเภทให้อยู่ในรูปที่ง่ายต่อการหา โดยเริ่มต้นจากการพิจารณาอนุพันธ์ของผลคูณของฟังก์ชัน
ต่อไปนี้ $$\frac{d}{dx} (uv) = v\frac{du}{dx} + u\frac{dv}{dx}$$ หรือ
เขียนให้อยู่ในรูปของ $$u(x) v'(x) = \frac{d}{dx}(u(x)v(x)) - v(x)u'(x)$$
โดยการหาปริพันธ์เทียบกับ $x$ เราจะได้ว่า
$$\int u(x) v'(x) dx = u(x)v(x) -  \int v(x)u'(x)dx$$ หรือ
$$\int u dv = uv -  \int v du$$ สูตรการหาปริพันธ์นี้ เรียกว่า integration by
parts

ในการใช้สูตรดังกล่าว เราจำเป็นที่จะต้องแบ่ง integrand ออกเป็น 2 ส่วนด้วยกัน คือ ส่วนของ
u และ dv โดยอาศัยหลักการต่อไปนี้

1.  ส่วน $dv$ ต้องเป็นส่วนที่ง่ายต่อการหาปริพันธ์

2.  ในพจน์ของ $\int v du$ จะต้องง่ายต่อการหา

::: example
จงหาปริพันธ์ของ $\int x e^x dx$
:::

::: example
จงหาปริพันธ์ของ $\int x \sin x dx$
:::

::: example
จงหาปริพันธ์ของ $\int e^x \sin 2x dx$
:::

::: example
จงหาปริพันธ์ของ $\int \ln xdx$
:::

::: example
จงหาปริพันธ์ของ $\int x \sqrt{x+1}dx$
:::

## การหาปริพันธ์โดยเศษส่วนย่อย (Integration by Partial Fractions)

เราจะศึกษาวิธีการหาปริพันธ์ของ rational ฟังก์ชัน หรือฟังก์ชันที่อยู่ในรูปของ
$$R(x) = \frac{P(x)}{Q(x)}$$ โดยที่ $P(x),Q(x)$ คือพหุนามใดๆ
ซึ่งจะเรียกวิธีต่อไปนี้ว่า partial fractions หลักการอยู่ที่การแยกเศษส่วน $R(x)$
ให้อยู่ในรูปของผลรวมต่อไปนี้ $$\label{partial-frac}
       R(x) = \frac{P(x)}{Q(x)} = p(x) + F_1(x) + F_2(x) + \ldots + F_m(x)$$
โดยที่ $p(x)$ คือ พหุนามที่ได้จากการหาร และ $F_k(x)$
จะเป็นเศษส่วนที่ง่ายต่อการหาปริพันธ์

พิจารณาตัวอย่างต่อไปนี้ $$\label{exa-partial-frac}
     \begin{split}
        \frac{-1+x^2+x^3+x^4}{x + x^3} &= 1 +x - \frac{x+1}{x + x^3}  \\
                                       &= 1 +x -\frac{1}{x} + \frac{x-1}{1+x^2} \\
     \end{split}$$ หลังการแยกเศษส่วน เราสามารถที่จะหาปริพันธ์ได้ง่ายขึ้น
$$\begin{aligned}
        \int \frac{-1+x^2+x^3+x^4}{x + x^3}dx &= \int\left(1 +x -\frac{1}{x} + \frac{x}{1+x^2} -\frac{1}{1+x^2}\right)dx \\   
            &=x + \frac{1}{2}x^2 - \ln|x| +\frac{1}{2}\ln(x^2+1) -\tan^{-1}x + C
    
\end{aligned}$$

ในการแยกเศษส่วน $R(x)$ ในสมการ
[\[partial-frac\]](#partial-frac){reference-type="ref"
reference="partial-frac"} ผลลัพธ์ที่ได้จะมีเศษส่วน $F_k(x)$ เพิ่มขึ้นมา โดยเศษส่วน
$F_k(x)$ นี้จะอยู่ในรูปของ $$\label{partial-frac-1}
     \frac{A}{(ax + b)^n} \text{ หรือ } \frac{Ax + B}{(ax^2 + bx +c)^n}$$
อย่างใดอย่างหนึ่ง (ซึ่งมีการพิสูจน์ในวิชาคณิตศาสตร์ขั้นสูง) และเราจะเรียกเศษส่วนนี้ว่า
partial fraction หรือเศษส่วนย่อย ตัวอย่างในสมการ
[\[exa-partial-frac\]](#exa-partial-frac){reference-type="ref"
reference="exa-partial-frac"} เศษส่วนย่อย คือ $-\frac{1}{x}$ และ
$\frac{x-1}{1+x^2}$

โดยทั่วไปเราสามารถจำแนก rational function ได้เป็น 2 ประเภท

1.  proper rational function ซึ่งเป็นกรณีที่ดีกรีของ $P(x)$ น้อยกว่าดีกรีของ $Q(x)$

2.  improper rational function ในกรณีนี้ดีกรีของ $P(x)$ มากกว่าหรือเท่ากับดีกรีของ
    $Q(x)$

ในสมการ [\[exa-partial-frac\]](#exa-partial-frac){reference-type="ref"
reference="exa-partial-frac"} rational function นี้เป็นแบบ improper
ดังนั้นเมื่อทำการตั้งหารยาวผลลัพท์ที่ได้จะเป็นผลบวกของพหุนาม $1 +x$ และ proper
rational function $- \frac{x+1}{x + x^3}$ ดังนั้นเราสามารถที่จะสมมติ ให้
rational function ของเราที่จะศึกษาต่อไปในบทนี้เป็น proper และเราจะหาวิธี ในการแยก
proper rational function ให้อยู่ในรูปผลรวมของเศษส่วนย่อยให้ได้
โดยเราจะเริ่มต้นจากกรณีที่ตัวประกอบของตัวหารเป็น linear factors
แล้วจึงพิจารณาในกรณีที่เป็น quadratic factors

**Linear Factors** สมมติให้ rational function $R(x) = \frac{P(x)}{Q(x)}$
เป็น proper และถ้าทำการแยกตัวประกอบของ $Q(x)$ แล้วมีเทอม $ax + b$ ซ้ำกันทั้งหมด
$n$ เทอม (นั่นคือ $(ax +b)^n$ เป็นตัวประกอบของ $Q(x)$) แล้วการแยก $R(x)$
เพื่อทำให้เป็นเศษส่วนย่อยจะต้องประกอบด้วย $n$ เทอมต่อไปนี้
$$\frac{A_1}{ax+b} +  \frac{A_2}{(ax+b)^2} + \cdots +  \frac{A_n}{(ax+b)^n}$$
โดยที่ $A_1, A_2, \ldots, A_n$ เป็นค่าคงตัว

::: example
**Distinct Linear Factors** จงหา $\int\frac{1}{x(x+1)} dx$
:::

**วิธีทำ** โดยการแยกหาเศษย่อย เราจะได้ว่า
$$\frac{1}{x(x+1)} = \frac{1}{x} - \frac{1}{x+1}$$

::: example
**Repeated Linear Factors** จงหา $\int\frac{1}{x^2(x+1)} dx$
:::

**วิธีทำ** โดยการแยกหาเศษย่อย เราจะได้ว่า
$$\frac{1}{x^2(x+1)} = -\frac{1}{x} + \frac{1}{x^2} + \frac{1}{x+1}$$

::: example
จงหาปริพันธ์ต่อไปนี้

1.  $\int \frac{x}{x^2+1} dx$

2.  $\int \frac{x^2+1}{x} dx$

3.  $\int \frac{1}{x(x+1)^2} dx$

4.  $\int \frac{1}{x^2(x+1)^2} dx$
:::

**วิธีทำ** เนื่องจาก
$$\frac{1}{x(x+1)^2} = \frac{1}{x} -\frac{1}{x+1} -\frac{1}{(x+1)^2}$$
และ
$$\frac{1}{x^2(x+1)^2} = \frac{1}{x^2} - \frac{2}{x} + \frac{2}{x+1} + \frac{1}{(1+x)^2}$$

**Quadratic Factors** ในกรณีที่ rational function
$R(x) = \frac{P(x)}{Q(x)}$ เป็น proper และ $(ax^2 +bx+c)^n$
เป็นตัวประกอบของ $Q(x)$ แล้วการแยก $R(x)$ เพื่อทำให้เป็นเศษส่วนย่อยจะต้องประกอบด้วย
$n$ เทอมต่อไปนี้
$$\frac{A_1x + B_1}{ax^2+bx+c} +  \frac{A_2x + B_2}{({ax^2+bx+c})^2} + \cdots +  \frac{A_nx + B_n}{({ax^2+bx+c})^n}$$

## ปริพันธ์ไม่ตรงแบบ (Improper Integrals)

ในการนิยาม definite integral $\int_{a}^{b} f(x) dx$ เราจะสมมติให้ฟังก์ชัน
$f(x)$ นี้นิยามบนช่วงปิด $[a,b]$ อย่างไรก็ตามในทางปฎิบัติเราอาจจะสนใจในกรณีต่อไปนี้

1.  กรณีที่ช่วงที่ใช้ในการหาปริพันธ์นั้นไม่ใช่ช่วงปิด เช่น
    $$[a, \infty) , (-\infty,b] \text{ หรือ } (-\infty,\infty)$$

2.  ตัว integrand $f(x)$ ไม่ต่อเนื่องที่จุดใดจุดหนึ่งบนช่วงของการหาปริพันธ์

และเราจะเรียก integral ใน 2 กรณีนี้ว่า improper integral
ในการหาปริพันธ์นี้เราจำเป็นที่จะต้องใช้เทคนิคพิเศษที่ช่วย
โดยเราจะเริ่มต้นจากการพิจารณาตัวอย่างต่อไปนี้

::: example
พิจารณา $\int_{1}^{\infty} \frac{1}{x^2} dx$
:::

**วิธีทำ** ค่าของปริพันธ์นี้ควรจะเป็นพื้นที่ที่อยู่ระหว่างกราฟ $y =  1/x^2$ แกน $x$
และเส้นตรง $x=1$ ถ้าเราพิจารณาช่วงปิด $[1,t]$ เราจะสามารถหาค่าของ
$$A(t) = \int_{1}^{t} \frac{1}{x^2} dx =  \left[-\frac{1}{x}\right]_{1}^{t} = 1 - \frac{1}{t}$$
ถ้าสมมติให้ $t \rightarrow \infty$ เราจะสามารถหาลิมิตของ $A(t)$
ได้ในกรณีซึ่งเท่ากับ 1 ดังนั้น เราจะนิยามให้พื้นที่ของบริเวณที่ถูกปิดล้อมด้วย $y =  1/x^2$
สำหรับ $x \in [1,\infty)$ เท่ากับค่าของลิมิตดังกล่าว และ
$$\int_{1}^{\infty} \frac{1}{x^2} dx = \lim_{t \rightarrow \infty} \int_{a}^t \frac{1}{x^2}dx = 
    \lim_{t \rightarrow \infty} (1 - \frac{1}{t}) = 1$$ โดยที่ลิมิตนี้หาค่าได้

จากตัวอย่างข้างต้น ทำให้เราสามารถสร้างนิยามได้ดังต่อไปนี้

::: definition
(Infinite Limits of Integration)

1.  []{#improper1 label="improper1"} ถ้า $\int_{a}^{t}f(x)dx$
    หาค่าได้สำหรับทุกๆ จำนวนจริง $t \ge a$ แล้ว
    $$\int_{a}^{\infty} f(x) dx  = \lim_{t \rightarrow \infty} \int_{a}^t f(x) dx$$
    ถ้าลิมิตหาค่าได้

2.  []{#improper2 label="improper2"} ถ้า $\int_{t}^{b}f(x)dx$
    หาค่าได้สำหรับทุกๆ จำนวนจริง $t \le b$ แล้ว
    $$\int_{-\infty}^{b} f(x) dx  = \lim_{t \rightarrow -\infty} \int_{t}^b f(x) dx$$
    ถ้าลิมิตหาค่าได้

ถ้าลิมิตในข้อ [\[improper1\]](#improper1){reference-type="ref"
reference="improper1"} และ
[\[improper2\]](#improper2){reference-type="ref" reference="improper2"}
หาค่าได้ เราจะเรียก improper integral นี้ว่า convergent แต่ถ้าลิมิตหาค่าไม่ได้ว่า
divergent เราจะเรียก integral นี้ว่า divergent

3.  ถ้า improper integrals $\int_{a}^{\infty} f(x) dx$ และ
    $\int_{-\infty}^{a} f(x) dx$ convergent แล้ว
    $$\int_{-\infty}^{\infty} f(x) dx  = 
                  \int_{-\infty}^{a} f(x) dx + \int_{a}^{\infty} f(x) dx$$
:::

::: example
จงหา $\int_{-\infty}^0 x e^x dx$
:::

**วิธีทำ** โดยการใช้ integration by part เราสามารถแสดงว่า
$$\int x e^x dx = x e^x - e^x +C$$ ดังนั้น $$\begin{aligned}
         \int_{-\infty}^0 x e^x dx &=  \lim_{t \rightarrow -\infty} \int_{t}^0 x e^x dx \\
                        &=  \lim_{t \rightarrow -\infty} (-t e^t -1 + e^t) = -1
    
\end{aligned}$$

สำหรับกรณีที่ตัว integrand $f(x)$ ไม่ต่อเนื่อง อาจจะไม่ต่อเนื่องที่จุด $c$ โดยที่ $c$
อาจจะเป็นจุดภายในช่วงปิด $[a,b]$ หรืออาจจะเป็นที่ขอบของช่วงปิดก็ได้
ในกรณีเราสามารถหาค่าของ improper integral ได้ดังต่อไปนี้

::: definition
[]{#def-improper label="def-improper"} (Infinite Integrands)

1.  []{#improper3 label="improper3"} ถ้า $f$ ต่อเนื่องบนช่วง $[a,b)$
    แต่ไม่ต่อเนื่องที่จุด $b$ แล้ว
    $$\int_{a}^b f(x) dx = \lim_{t \rightarrow b^{-}} \int_{a}^t f(x) dx$$
    ถ้าลิมิตนี้หาค่าได้

2.  []{#improper4 label="improper4"} ถ้า $f$ ต่อเนื่องบนช่วง $(a,b]$
    แต่ไม่ต่อเนื่องที่จุด $a$ แล้ว
    $$\int_{a}^b f(x) dx = \lim_{t \rightarrow a^{+}} \int_{t}^b f(x) dx$$
    ถ้าลิมิตนี้หาค่าได้

ถ้าลิมิตในข้อ [\[improper3\]](#improper3){reference-type="ref"
reference="improper3"} และ
[\[improper4\]](#improper4){reference-type="ref" reference="improper4"}
หาค่าได้ เราจะเรียก improper integral นี้ว่า convergent แต่ถ้าลิมิตหาค่าไม่ได้ว่า
divergent เราจะเรียก integral นี้ว่า divergent

3.  ถ้า $f$ ไม่ต่อเนื่องที่จุด $c$ โดยที่ $a < c <b$ และ $\int_{a}^{c} f(x) dx$
    และ $\int_{c}^{b} f(x) dx$ convergent แล้ว $$\int_{a}^{b} f(x) dx  = 
                  \int_{a}^{c} f(x) dx + \int_{c}^{b} f(x) dx$$
:::

::: example
จงหา $\int_{1}^{5} \frac{1}{\sqrt{x-1}} dx$
:::

**วิธีทำ** เราสามารถใช้นิยาม
[\[def-improper\]](#def-improper){reference-type="ref"
reference="def-improper"} ในการหาค่าปริพันธ์ดังต่อไปนี้ $$\begin{aligned}
  \int_{1}^{5} \frac{1}{\sqrt{x-1}} dx &= \lim_{t \rightarrow 1^{+} }\int_{t}^{5} \frac{1}{\sqrt{x-1}} dx \\
         &= \lim_{t \rightarrow 1^{+}} 2\sqrt{x-1} |_{t}^{5} \\
         &= \lim_{t \rightarrow 1^{+}} (4 - 2\sqrt{t-1}) = 4           
    
\end{aligned}$$ ดังนั้น improper integral นี้จะ converge เข้าสู่ค่า 4

::: example
จงหา $\int_{-1}^{1} \frac{1}{x^2} dx$
:::

**วิธีทำ** เนื่องจาก $f(x)$ ไม่ต่อเนื่องที่จุด 0 ดังนั้นเราสามารถใช้นิยาม
[\[def-improper\]](#def-improper){reference-type="ref"
reference="def-improper"} ในการหาค่าปริพันธ์ดังกล่าว $$\begin{aligned}
        \int_{-1}^{1} \frac{1}{x^2} dx &= \lim_{t \rightarrow 0^{-} }\int_{-1}^{t} \frac{1}{x^2}dx
                                            + \lim_{s \rightarrow 0^{+}} \int_{s}^{1} \frac{1}{x^2}dx \\
        &= \lim_{t \rightarrow 0^{-}} \left[ -\frac{1}{x}\right]_{-1}^t 
        + \lim_{s \rightarrow 0^{+}} \left[ -\frac{1}{x}\right]_{s}^1 \\
        &= \lim_{t \rightarrow 0^{-}} (-\frac{1}{t} - 1) + \lim_{s \rightarrow 0^{+}} (-1 +\frac{1}{s})
    
\end{aligned}$$ แต่เนื่องจากลิมิตในบรรทัดสุดท้ายนี้หาค่าไม่ได้ เราจึงสรุปว่า
$\int_{-1}^{1} \frac{1}{x^2} dx$ เป็น divergent

หมายเหตุถ้าเราไม่ใช่วิธีเบื้องต้น โดยเลือกที่จะคำนวณโดยตรงโดยไม่สนใจจุดที่ฟังก์ชันไม่ต่อเนื่อง
เราจะได้ว่า
$$\int_{-1}^{1} \frac{1}{x^2} dx  = \left[ -\frac{1}{x}\right]_{-1}^1 = -1 + -1 = -2$$
ซึ่งไม่ใช่ผลลัพธ์ที่ถูกต้อง (เพราะว่ากราฟ $y = \frac{1}{x^2}$ อยู่เหนือแกน $x$ ดังนั้น
$\int_{-1}^{1} \frac{1}{x^2} dx$ จะต้องมีค่าที่เป็นบวก)

## แบบฝึกหัด {#แบบฝกหด-1}

**ตอนที่ 1** **ตอนที่ 2** จงหา improper integrals ต่อไปนี้

:::: enumerate
::: multicols
2

$\int_{1}^{\infty} \frac{1}{\sqrt{x+1}} dx$ divergent

$\int_{1}^{\infty} \frac{1}{(x+1)^{3/2}}dx = \sqrt{2}$

$\int_{-\infty}^{-1} \frac{1}{(2x + 1)^2} dx = \frac{1}{2}$

$\int_{-\infty}^{\infty} x e^{-x^2} dx = 0$

$\int_{1}^{\infty} \frac{\ln x}{x^2}  dx = 1$

$\int_0^1 \frac{1}{\sqrt{1-x}} dx = 2$

$\int_0^{1} \frac{x}{x^2-1} dx$ divergent

$\int_0^{1/2} \frac{x}{x^2-1} dx = -\frac{1}{2} \ln (\frac{4}{3})$
:::
::::
